---
title: Switching to blogdown, netlify and travis
author: Lorenz Walthert
date: '2018-06-12'
slug: getting-up-and-running-with-blogdown-netlify-and-travis
description: How I switched from Jekyll to blogdown and got travis to build 
  my page and deploy it with netlify.
categories:
  - R
tags:
  - writing
---

## The problem
Some time ago, I started a blog. I actually did not post a whole lot of stuff 
though. I was using Jekyll, but my set-up was rather brittle and there were 
a few problems:

- I could not use Rmarkdown directly. I always had to knitr manually to get 
  plain markdown from my Rmarkdown files and then use them as input for Jekyll. 
  Since the majority of my posts 
  involved at least some R code, this was not a very elegant thing to do.
- Since every Rmarkdown post had to be converted into plain markdown in a (
  more or less) manual way, I could not use automated builds on GitHub Pages. 
- This, in turn, meant I had to build the content locally and commit all 
  derivatives (i.e. html documents), which isn't very elegant either.
  

## The solution

Below, I outline how I managed to address these three problems with the three
tools: blogdown to create content, netlify to deploy the website and travis to 
automate the build and deployment step. My approach does not require html or
markdown derivatives (from Rmarkdown files) to be committed (and pushed) in git, 
which I think is nice and helps keeping the repo lightweight.
But let's go step by step.

### Step 1: Creating content

I started my journey reading up on 
[blogdown](https://bookdown.org/yihui/blogdown/), which I think was a good
starting point. When I got the basics, I checked out the 
[huog theme gallery](https://themes.gohugo.io/). I was looking for a simplistic
theme, and I found one: [cactus plus](https://themes.gohugo.io/hugo-theme-cactus-plus/).
As advised by Yihui, I created a new RStudio Project and ran
`blogdown::new_site(theme = "nodejh/hugo-theme-cactus-plus")`. So far so good.
I copied over some of my old blog posts into this directory and adapted the YAML
headers to match the format of the example posts, which worked smoothly.
Next, I adapted some configurations using the explanations in the 
[cactus plus README](https://github.com/nodejh/hugo-theme-cactus-plus#example-site).
In particular, I did the following:

* Adapted the avatar, title and subtitle of the webpage.
* Set `useDescriptionReplaceSummary` in `config.toml` to `true` to use the 
  custom description from the YAML header for each post.
* Added my `disqus` and `google_analytics` user name to `config.toml`.
* Most importantly, **I set the base url to "/"** in in `config.toml`. Note 
  that the base URL should in any case end with a back slash, otherwise certain
  pages won't render correctly, i.e. the `tags` page.

Now that I had the content, I had to think about how to deploy the page.

### Step 2: Deploying the page

I read the section [on deployment](https://bookdown.org/yihui/blogdown/deployment.html) in the blogdown documentation, but it was not particularly revealing to me. First and foremost, 
it was not clear to me how I can build the page with netlify since
the build commands `hugo` and `jekyll` were not able to convert Rmarkdown into
html - or at least that's what I thought. A quick Google search did not 
help much either. I then realized I might want to use the 
[netlify cli tools](https://www.netlify.com/docs/cli/) to deploy a locally
built site with netlify. The only problem with that was that these only seemed 
to work properly on Linux, which is not my primary operating system. Anyways, I 
managed to deploy a page from my Linux environment with netlify. It's pretty 
straightforward once you managed to build your website locally and stored it 
in the `public/` directory. Here is what I did:

* use the RStudio Addin Serve Site (or `blogdown::serve_site()`), which 
  updates your static site in the self-containing publishing directory, 
  `public/` by default.
* Following the video in the 
  [netlify cli tools documentation](https://www.netlify.com/docs/cli/), i.e.
  essentially `$ netlify deploy` my `public/` folder.
  
Also, I changed the publishing URL in the netlify settings, so my page would 
be available under `lorenzwalthert.netlify.com`. You can also use a custom 
non-netlify domain.

Alternatively, you can commit and push markdown or html derivatives of your 
Rmarkdown files and use the netlify build command `hugo`, potentially specifying
the hugo version as part of the bulid command (like `hugo_0.19`) or via an 
environment variable. However, I refrained from doing this because I felt like
this approach was not as clean as building the whole page on a remote CI tool.

### Step 3a: Automatically deploy the page

Finally, deploying the page manually every time you make a change seems like a
step that could be automatized - and it is. I had no idea how though. For some 
reason, I knew that the [tidyverse style guide](http://style.tidyverse.org) 
gets deployed automatically with netlify, so I looked at the GitHub repo to 
figure out how it might work. I realized that they use travis to do the 
deployment. I inspected the `.travis.yml` file and copied it over to my repo.
After tweaking it a little, I ended up with the following `.travis.yml` file:

```
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache:
  packages: true
  directories:
  - $HOME/.npm

before_install:
- npm install netlify-cli -g
- Rscript -e 'blogdown::install_hugo()'

script:
- Rscript -e 'blogdown::build_site()'

deploy:
  provider: script
  script: netlify deploy -t $NETLIFYKEY
  skip_cleanup: true
```

In addition, I found [this](https://therocketeers.github.io/blog/using-travis-ci-to-deploy-jekyll-on-netlify/) blog post, where I learned how I could create an 
access token for netlify which I could pass to travis so it has the 
privileges to deploy to netlify. Essentially you go [here](https://app.netlify.com/applications) and create a new access
token, which you in turn add a hidden environment variable in the travis 
settings of the repo that contains the source code for the webpage to deploy. 
This environment variable is used in the deploy step in the script above, so if 
you want to use this script, you need to call the variable `NETLIFYKEY`. 
The `-t` flag in
the deployment command stands for `token`. Do **not** hard-code your token into 
the deployment command but use the environment variable as shown above, except 
you want to share the access credentials of your netlify account with the world.

There were only two more steps to complete:

* Add a DESCRIPTION file to my repo and add the dependencies I used in my 
  R code to it, which you
  can do most conveniently with `usethis::use_package("your_package")` after 
  you added a basic DESCRIPTION file. 
  Alternatively, you can add install commands to your `.travis.yaml` file but 
  I think the DESCRIPTION solution is nicer.
* Copied the `.netlify` file from my local Linux environment from which I have 
  already successfully deployed the page. The file is created in the root 
  directory of your blogdown project. Don't know exactly what it does, but 
  I think it creates some *deplyoment context* that is used when you call 
  `$ netlify deploy`, 
  i.e. it does not prompt the user to give further instructions such as the 
  directory that contains the files to deploy. This is helpful because you can't
  give interactive instructions to travis during the build process.
  I also found this file in the 
  [tidyverse style guide repo](https://github.com/tidyverse/style) so I figured 
  that this was the last missing piece.


### Step 3b: Automatically deploy the page with merge preview

This was it. The next build succeeded and my site got deployed. A nice feature
of netlify is also that you can pre-view rendered pull requests before you 
merge them, so you can detect dead links, missing pictures etc. When I clicked 
on the netlify CI link in the PR on GitHub, I got an empty page. What was that? 
After skimming through my netlify settings, I discovered that the build command
was set to `hugo`. When I run `$ hugo` locally, I got the same result as the 
netlify preview. Hugo was expecting either html or markdown files, but I only
had Rmarkdown. So just as for the regular build process, I could not use netlify
to build my page. Dang.

I checked out the [tidyverse.org](https://github.com/tidyverse/tidyverse.org)
website from which I knew that they had netlify previews. The way it works (
as of June 2018) was that people had to locally serve the site and also commit
the derivaties, i.e. the html pages, which is basically equivalent to the 
approach mentioned in the last paragraph of Step 2. Since I already achieved 
deploying the page with travis and netlify without committing any derivaties, I 
felt like it could not be all that complicated to do the same for PRs.

A few hours later, I figured out how to do it.

* First, you need to know that in the above script, the deployment happens 
  only for the production branch. Hence, you need to use `after_success:` in 
  `.travis.yml` instead of `deploy:`, the former getting executed for every 
  branch.
* Then, I wrote a little bash script that
    * First checks if the current branch is the master branch or some other 
      branch.
    * Depending on that, either do a normal deploy of the page (in case we are
      on master) or only deploy a draft.


## Roundup

 You should
be able to see the links to the relevant netlify domain in your CI checks.

Overall, I am pretty happy with the set-up now. In case you are interested in 
some of the details I skipped above, feel free to reach out to me via the 
comment below.